### ISSUE TITLE
Is it possible to get the attempt number?

### ISSUE THREAD

**Issue by amaury1093** [gcanti/retry-ts#5]
In the example in the README, I would like to also log the attempt number, something like:

```typescript
const logDelay = (delay: number, attempt: number) => TE.rightIO(log(`Attempt #${attempt} failed, retrying in ${delay} milliseconds`))
```

Right now, I'm setting a `let attempt = 0;` outside of the `retrying()` function, and doing a side effect to increment it on every retry. But maybe there's a cleaner way?

**Comment by gcanti** [comment]
you can leverage the `iterNumber ` field https://gcanti.github.io/retry-ts/modules/index.ts.html#retrystatus-interface

**Comment by amaury1093** [comment]
Thanks, that works.

Follow-up question: how about if I want to show, on each retry, the error message returned by the previous (failed) attempt?

**Comment by saharrachamimfg** [comment]
+1 for the follow-up question:

> how about if I want to show, on each retry, the error message returned by the previous (failed) attempt?

**Comment by SRachamim** [comment]
+1 for the follow-up question:

> how about if I want to show, on each retry, the error message returned by the previous (failed) attempt?
